### ISSUE TITLE
WPF samples

### ISSUE THREAD

**Issue by airelil** [pywinauto/PywinautoTestapps#3]
Since the [PR#2](https://github.com/pywinauto/PywinautoTestapps/pull/2) we got two solution files: one for MFC samples and one for WPF. I think Visual Studio handles well mixed C++/C# solutions so I suggest that we include projects with WPF samples into the existing MFC solution. Maybe it should be renamed to a more general _TestApps.sln_ instead of _MfcTestApps.sln_

**Comment by vasily-v-ryabov** [comment]
Agree. We need to reduce the number of samples as much as possible.
Sure, VS handles any kinds of projects inside one solution.
